### ISSUE TITLE
plans for v3.public

### ISSUE THREAD

**Issue by Eh2406** [rrrodzilla/rusty_paseto#24]
What is your plans re v3.public will you be supporting it? If so do you have an ETA?

**Comment by rrrodzilla** [comment]
Hey, thanks for reaching out.

I shipped without v3.public because there was some question as to whether or not the cryptography crate I intended to use for the ECDSA cipher used point compression.  Also, it wasn't a cipher combo I needed for my use case.  Implementation is straightforward and shouldn't take longer than a few days to a week.   However, I'm focusing all my efforts on a job search, so I won't be able to get started on it until I've gained employment and settled into that.

I'll prioritize it in my current roadmap and update this issue once it's ready!

**Comment by rrrodzilla** [comment]
Happy new year! v0.5.0 with V3 Public support is now released.
